# Множинна регресія та попереднє опрацювання даних
Множинна регресія дозволяє знаходити залежності від кількох параметрів.
Більш того, дозволяє провести оцінку внеску цих параметрів у результат.

## Завдання 1
Побудуйте модель лінійної регресії на кількох ознаках датасету California Housing:
- Завантажте датасет зі scikit-learn.
- Сформуйте DataFrame з ознаками та цільовою змінною.
- Виберіть 3 ознаки, наприклад: MedInc, HouseAge, AveRooms.
- Розділіть дані на навчальну і тестову вибірки (80/20, random_state=42).
- Навчіть модель LinearRegression і отримайте передбачення.
- Обчисліть R² на тестовій вибірці та виведіть результат у таблиці.

In [1]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

In [4]:
california_housing = fetch_california_housing(as_frame=True)
california_housing.frame.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [5]:
print(california_housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib:
https://lib.stat.cmu.edu/datasets/houses.zip

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.

In [7]:
# Виберіть 3 ознаки, наприклад: MedInc, HouseAge, AveRooms.
housing = california_housing.frame[['MedInc', 'HouseAge', 'AveRooms']]
housing.head()

   MedInc  HouseAge  AveRooms
0  8.3252      41.0  6.984127
1  8.3014      21.0  6.238137
2  7.2574      52.0  8.288136
3  5.6431      52.0  5.817352
4  3.8462      52.0  6.281853

In [8]:
# Розділіть дані на навчальну і тестову вибірки (80/20, random_state=42).
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(housing, california_housing.target, test_size=0.2, random_state=42)

print(f"Train: {len(ytrain)}, test: {len(ytest)}")

Train: 16512, test: 4128

In [9]:
# Навчіть модель LinearRegression і отримайте передбачення.
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(xtrain, ytrain)

LinearRegression()

In [15]:
pred = model.predict(xtest)
print(*(f"{p:.2f} -- {y:.2f}" for p,y in zip(pred[:10], ytest[:10])), sep='\n')

1.07 -- 0.48
1.51 -- 0.46
2.33 -- 5.00
2.68 -- 2.19
2.09 -- 2.78
2.17 -- 1.59
2.71 -- 1.98
2.16 -- 1.57
2.11 -- 3.40
4.19 -- 4.47

In [17]:
# Обчисліть R² на тестовій вибірці та виведіть результат у таблиці.
import sklearn.metrics as sm
r2_base = sm.r2_score(ytest, pred)
print("Коефіцієнт детермінації моделі", r2_base)

Коефіцієнт детермінації моделі 0.49717158850807075

## Завдання 2
Перевірте вплив масштабування на роботу лінійної регресії:
- Використовуйте ті самі ознаки (MedInc, HouseAge, AveRooms).
- Навчіть модель без масштабування і порахуйте R².
- Масштабуйте ознаки за допомогою StandardScaler і навчіть нову модель.
- Порахуйте R² після масштабування.
- Порівняйте результати в таблиці:

|Модель|Масштабування|R²|
|-|-|-|
|LinearRegression|Ні|...|
|LinearRegression|StandardScaler|...|

In [20]:
# Масштабуйте ознаки за допомогою StandardScaler ...
from sklearn.preprocessing import StandardScaler
print(housing.head())
scaler = StandardScaler()
data = scaler.fit_transform(housing)
print(data[:5])

   MedInc  HouseAge  AveRooms
0  8.3252      41.0  6.984127
1  8.3014      21.0  6.238137
2  7.2574      52.0  8.288136
3  5.6431      52.0  5.817352
4  3.8462      52.0  6.281853
[[ 2.34476576  0.98214266  0.62855945]
 [ 2.33223796 -0.60701891  0.32704136]
 [ 1.7826994   1.85618152  1.15562047]
 [ 0.93296751  1.85618152  0.15696608]
 [-0.012881    1.85618152  0.3447108 ]]

In [21]:
# ... і навчіть нову модель.
xtrain2, xtest2, ytrain2, ytest2 = train_test_split(data, california_housing.target, test_size=0.2, random_state=42)
model2 = LinearRegression()
model2.fit(xtrain2, ytrain2)

LinearRegression()

In [23]:
r2_scaled = sm.r2_score(ytest2, model2.predict(xtest2))
from IPython.display import Markdown as md
md(f"""|Модель|Масштабування|R²|
|-|-|-|
|LinearRegression|Ні|{r2_base}|
|LinearRegression|StandardScaler|{r2_scaled}|
""")

|Модель|Масштабування|R²|
|-|-|-|
|LinearRegression|Ні|0.49717158850807075|
|LinearRegression|StandardScaler|0.49717158850807075|

## Завдання 3
Застосуйте різні методи попередньої обробки даних:
- Додайте в DataFrame штучну категоріальну ознаку, наприклад:
import numpy as np 
df['Category'] = np.where(df['HouseAge'] > 30, 'Old', 'New')

- Перетворіть цю ознаку:
    - за допомогою factorize;
    - за допомогою OneHotEncoder.
- Додайте штучні пропуски в 1 колонку (наприклад, MedInc), заповніть їх через SimpleImputer (середнім значенням).
- Навчіть модель лінійної регресії та порівняйте R² для різних способів кодування категоріальної ознаки.

In [24]:
import numpy as np 
housing['Category'] = np.where(housing['HouseAge'] > 30, 'Old', 'New')
housing.head()

   MedInc  HouseAge  AveRooms Category
0  8.3252      41.0  6.984127      Old
1  8.3014      21.0  6.238137      New
2  7.2574      52.0  8.288136      Old
3  5.6431      52.0  5.817352      Old
4  3.8462      52.0  6.281853      Old

In [26]:
housing["factorize"] = pd.factorize(housing['Category'])[0]
housing.head()

   MedInc  HouseAge  AveRooms Category  factorize
0  8.3252      41.0  6.984127      Old          0
1  8.3014      21.0  6.238137      New          1
2  7.2574      52.0  8.288136      Old          0
3  5.6431      52.0  5.817352      Old          0
4  3.8462      52.0  6.281853      Old          0

In [33]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, drop='first')  # sparse_output - формувати матрицю чи масив, drop - видалення додаткових варіантів
housing["encoder"] = encoder.fit_transform(housing['Category'].array.reshape(-1, 1))
housing.head()

   MedInc  HouseAge  AveRooms Category  factorize  encoder
0  8.3252      41.0  6.984127      Old          0      1.0
1  8.3014      21.0  6.238137      New          1      0.0
2  7.2574      52.0  8.288136      Old          0      1.0
3  5.6431      52.0  5.817352      Old          0      1.0
4  3.8462      52.0  6.281853      Old          0      1.0

In [34]:
def score_model(data) :
    model = LinearRegression()
    xtrain, xtest, ytrain, ytest = train_test_split(data, california_housing.target, test_size=0.2, random_state=42)
    model.fit(xtrain, ytrain)
    return sm.r2_score(ytest, model.predict(xtest)), model

In [35]:
score1, model1 = score_model(housing[['MedInc', 'HouseAge', 'AveRooms', 'factorize']])
print(score1)
model1

0.49813639363825635

LinearRegression()

In [36]:
score1, model1 = score_model(housing[['MedInc', 'HouseAge', 'AveRooms', 'encoder']])
print(score1)
model1

0.49813639363825635

LinearRegression()

In [37]:
# Додайте штучні пропуски в 1 колонку (наприклад, MedInc), ...
ind = [10,20,30,40,50]
housing.loc[ind, "MedInc"] = None
housing.loc[ind, "MedInc"]

10   NaN
20   NaN
30   NaN
40   NaN
50   NaN
Name: MedInc, dtype: float64

In [38]:
# ... заповніть їх через SimpleImputer (середнім значенням).
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="mean")
housing["MedInc"] = imputer.fit_transform(housing["MedInc"].array.reshape(-1,1))
housing.loc[ind, "MedInc"]

10    3.871148
20    3.871148
30    3.871148
40    3.871148
50    3.871148
Name: MedInc, dtype: float64

In [39]:
california_housing.frame.loc[ind, "MedInc"]

10    3.2031
20    1.3578
30    1.9274
40    2.0978
50    0.9218
Name: MedInc, dtype: float64

In [40]:
score1, model1 = score_model(housing[['MedInc', 'HouseAge', 'AveRooms', 'encoder']])
print(score1)
model1

0.4982831843477207

LinearRegression()

## Завдання 4
Оцініть модель за допомогою крос-валідації та проаналізуйте перенавчання:
- Використовуйте всі числові ознаки датасету California Housing.
- Застосуйте StandardScaler для нормалізації даних.
- Навчіть модель лінійної регресії.
- Оцініть її якість за допомогою cross_val_score (k=5, метрика R²).
- Виведіть середнє значення і стандартне відхилення R².
- Порівняйте результати зі звичайним train/test розбиттям.

In [49]:
scaler = StandardScaler()
data = scaler.fit_transform(california_housing.frame.drop(columns=['MedHouseVal']))
data[:5]

array([[ 2.34476576,  0.98214266,  0.62855945, -0.15375759, -0.9744286 ,
        -0.04959654,  1.05254828, -1.32783522],
       [ 2.33223796, -0.60701891,  0.32704136, -0.26333577,  0.86143887,
        -0.09251223,  1.04318455, -1.32284391],
       [ 1.7826994 ,  1.85618152,  1.15562047, -0.04901636, -0.82077735,
        -0.02584253,  1.03850269, -1.33282653],
       [ 0.93296751,  1.85618152,  0.15696608, -0.04983292, -0.76602806,
        -0.0503293 ,  1.03850269, -1.33781784],
       [-0.012881  ,  1.85618152,  0.3447108 , -0.03290586, -0.75984669,
        -0.08561576,  1.03850269, -1.33781784]])

In [51]:
model = LinearRegression()
model.fit(data, california_housing.target)

LinearRegression()

In [52]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, data, california_housing.target, cv=5, scoring="r2")

array([0.54866323, 0.46820691, 0.55078434, 0.53698703, 0.66051406])

Перенавчання - ефект "запам'ятовування" усіх тестових прикладів і одержання ідеальних оцінок для прогнозів при
проведенні тестів на базі цих же прикладів.

In [53]:
model.coef_

array([ 0.8296193 ,  0.11875165, -0.26552688,  0.30569623, -0.004503  ,
       -0.03932627, -0.89988565, -0.870541  ])