# Pandas
*pip install pandas*

In [1]:
import pandas as pd

## Завдання 1
У вас є дані про користувачів із полями: "Ім'я", "Вік" і "Місто".
- Створіть DataFrame зі словника Python із п'ятьма записами.
- Виведіть весь DataFrame.
- Визначте кількість рядків і стовпців.
- Виведіть назви всіх стовпців.
- Покажіть перші три рядки таблиці.

DataFrame - об'єкт, що представляє дані змішаного типу за принципом таблиці (колонки та рядки), що відображають таблиці баз даних.
Створювати їх можна як з наведеного переліку, так і зі збережених даних, зокрема, CSV-файлів

In [4]:
pd.DataFrame({                   # Наявні дані подаються dict            
    "col-1": [1,2,3],            # ключі - відповідають за колонки
    "col-2": ['a','b','c'],      # значення - масиви даних
    "col-3": [1.0, 2.0, None],   # всі масиви мають бути однакової довжини, якщо є пропуски даних                         
})                               # то залишаємо None

   col-1 col-2  col-3
0      1     a    1.0
1      2     b    2.0
2      3     c    NaN

In [6]:
# create please data dict for pandas dataframe with fields "Name", "Age", "City" and 10 lines
data = {
    "Name": [
        "Alice", "Bob", "Charlie", "Diana", "Ethan",
        "Fiona", "George", "Hannah", "Ian", "Julia"
    ],
    "Age": [
        25, 30, 22, 28, 35,
        27, 40, 24, 31, 29
    ],
    "City": [
        "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
        "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose"
    ]
}
people = pd.DataFrame(data)
people

      Name  Age          City
0    Alice   25      New York
1      Bob   30   Los Angeles
2  Charlie   22       Chicago
3    Diana   28       Houston
4    Ethan   35       Phoenix
5    Fiona   27  Philadelphia
6   George   40   San Antonio
7   Hannah   24     San Diego
8      Ian   31        Dallas
9    Julia   29      San Jose

In [16]:
# Визначте кількість рядків і стовпців.
print(f"Кількість рядків: {len(people.index)}, кількість стовпців: {len(people.columns)}")
# Виведіть назви всіх стовпців.
print("назви всіх стовпців:", ", ".join(people.columns))

Кількість рядків: 10, кількість стовпців: 3
назви всіх стовпців: Name, Age, City

In [18]:
# Покажіть перші три рядки таблиці.
people.head(3)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago

## Завдання 2
У файлі CSV збережено дані про фільми: "Назва", "Жанр", "Рік", "Рейтинг".
- Прочитайте дані з CSV у DataFrame.
- Виведіть перші п'ять рядків таблиці.
- Визначте загальну кількість рядків і стовпців.
- Визначте типи даних для кожного стовпця.
- Перевірте наявність пропусків.

In [26]:
# Згенеруй файл CSV з даними про фільми: "Назва", "Жанр", "Рік", "Рейтинг" кількістю 50 рядків
movies = pd.read_csv("./Pract2_2_movies.csv")
# Виведіть перші п'ять рядків таблиці.
movies.head()

      Назва      Жанр     Рік  Рейтинг
0  Movie 01    Action  1983.0      5.1
1  Movie 02     Drama  1986.0      5.2
2  Movie 03    Comedy  1989.0      5.3
3  Movie 04    Sci‑Fi  1992.0      5.4
4  Movie 05  Thriller  1995.0      5.5

In [27]:
# Визначте загальну кількість рядків і стовпців.
print(f"Кількість рядків: {len(movies.index)}, кількість стовпців: {len(movies.columns)}")

Кількість рядків: 50, кількість стовпців: 4

In [28]:
# Визначте типи даних для кожного стовпця.
print("типи даних для кожного стовпця:", movies.dtypes, sep='\n')

типи даних для кожного стовпця:
Назва          str
Жанр           str
Рік        float64
Рейтинг    float64
dtype: object

In [31]:
# Перевірте наявність пропусків.  -- корегуємо файл, видаляємо декілька даних
movies.isnull().head(11)

    Назва   Жанр    Рік  Рейтинг
0   False  False  False    False
1   False  False  False    False
2   False  False  False    False
3   False  False  False    False
4   False  False  False    False
5   False  False  False    False
6   False  False  False    False
7   False  False  False    False
8   False   True  False    False
9   False  False   True    False
10  False  False  False     True

In [38]:
# Розширюємо задачу: вивести індекси пропусків даних
import numpy as np
positions = np.where( movies.isnull() )  # (array([ 8,  9, 10]), array([1, 2, 3]))
print(f"Загальна кількість пропусків: {len(positions[0])}")
print("Їх індекси:",  ", ".join(f"({x};{y})" for (x,y) in zip(*positions)))

Загальна кількість пропусків: 3
Їх індекси: (8;1), (9;2), (10;3)

## Завдання 3
Є таблиця співробітників із колонками: "Ім'я", "Вік", "Відділ", "Зарплата".
- Створіть DataFrame з не менш ніж п'ятьма рядками.
- Виведіть усі рядки, де зарплата вища за 50000.
- Відсортуйте таблицю за віком у порядку зростання.
- Відсортуйте таблицю за зарплатою в порядку спадання.

In [39]:
data = {
    "Ім'я": [
        "Олександр",
        "Марія",
        "Іван",
        "Анна",
        "Дмитро",
        "Олена",
        "Андрій",
        "Наталія",
        "Сергій",
        "Ірина"
    ],
    "Вік": [
        28, 34, 25, 31, 40,
        29, 36, 27, 45, 33
    ],
    "Відділ": [
        "Продажі",
        "Маркетинг",
        "ІТ",
        "Фінанси",
        "HR",
        "ІТ",
        "Продажі",
        "Маркетинг",
        "Фінанси",
        "HR"
    ],
    "Зарплата": [
        45000,
        52000,
        68000,
        57000,
        50000,
        72000,
        48000,
        55000,
        62000,
        51000
    ]
}
workers = pd.DataFrame(data)
workers

        Ім'я  Вік     Відділ  Зарплата
0  Олександр   28    Продажі     45000
1      Марія   34  Маркетинг     52000
2       Іван   25         ІТ     68000
3       Анна   31    Фінанси     57000
4     Дмитро   40         HR     50000
5      Олена   29         ІТ     72000
6     Андрій   36    Продажі     48000
7    Наталія   27  Маркетинг     55000
8     Сергій   45    Фінанси     62000
9      Ірина   33         HR     51000

In [40]:
# Виведіть усі рядки, де зарплата вища за 50000.
workers[ workers["Зарплата"] > 50000 ]

      Ім'я  Вік     Відділ  Зарплата
1    Марія   34  Маркетинг     52000
2     Іван   25         ІТ     68000
3     Анна   31    Фінанси     57000
5    Олена   29         ІТ     72000
7  Наталія   27  Маркетинг     55000
8   Сергій   45    Фінанси     62000
9    Ірина   33         HR     51000

In [41]:
# Відсортуйте таблицю за віком у порядку зростання.
workers.sort_values(by="Вік", ascending=True)

        Ім'я  Вік     Відділ  Зарплата
2       Іван   25         ІТ     68000
7    Наталія   27  Маркетинг     55000
0  Олександр   28    Продажі     45000
5      Олена   29         ІТ     72000
3       Анна   31    Фінанси     57000
9      Ірина   33         HR     51000
1      Марія   34  Маркетинг     52000
6     Андрій   36    Продажі     48000
4     Дмитро   40         HR     50000
8     Сергій   45    Фінанси     62000

In [42]:
# Відсортуйте таблицю за зарплатою в порядку спадання.
workers.sort_values(by="Зарплата", ascending=False)

        Ім'я  Вік     Відділ  Зарплата
5      Олена   29         ІТ     72000
2       Іван   25         ІТ     68000
8     Сергій   45    Фінанси     62000
3       Анна   31    Фінанси     57000
7    Наталія   27  Маркетинг     55000
1      Марія   34  Маркетинг     52000
9      Ірина   33         HR     51000
4     Дмитро   40         HR     50000
6     Андрій   36    Продажі     48000
0  Олександр   28    Продажі     45000

## Завдання 4
Доступні дані про продажі з колонками: "Товар", "Категорія", "Ціна", "Кількість".
- Створіть DataFrame з не менш ніж десятьма рядками.
- Виведіть вихідний DataFrame.
- Додайте новий стовпець "Виручка" як добуток ціни та кількості.
- Виведіть оновлений DataFrame.

data = {
    "Product": [
        "Laptop", "Smartphone", "Tablet", "Monitor", "Keyboard",
        "Mouse", "Printer", "Scanner", "Webcam", "Headphones",
        "Speaker", "Router", "SSD", "Hard Drive", "USB Flash Drive",
        "Power Bank", "Smartwatch", "Camera", "Microphone", "Projector",
        "Graphics Card", "Motherboard", "Processor", "RAM", "Cooling Fan",
        "Desk Lamp", "Office Chair", "Standing Desk", "Notebook", "Pen Set",
        "Backpack", "External SSD", "Docking Station", "Network Switch", "Cable Organizer",
        "Wireless Charger", "Bluetooth Adapter", "Gaming Mouse", "Gaming Keyboard", "VR Headset",
        "Smart TV", "Streaming Device", "Fitness Tracker", "E-Reader", "Drone",
        "Action Camera", "Tripod", "Ring Light", "NAS Storage", "Mini PC"
    ],
    "Category": [
        "Electronics", "Electronics", "Electronics", "Electronics", "Accessories",
        "Accessories", "Office Equipment", "Office Equipment", "Accessories", "Audio",
        "Audio", "Networking", "Storage", "Storage", "Storage",
        "Accessories", "Wearables", "Photography", "Audio", "Electronics",
        "Computer Components", "Computer Components", "Computer Components", "Computer Components", "Computer Components",
        "Office Supplies", "Furniture", "Furniture", "Office Supplies", "Office Supplies",
        "Accessories", "Storage", "Accessories", "Networking", "Accessories",
        "Accessories", "Accessories", "Gaming", "Gaming", "Gaming",
        "Electronics", "Electronics", "Wearables", "Electronics", "Photography",
        "Photography", "Photography", "Photography", "Storage", "Computer Components"
    ],
    "Price": [
        1200, 800, 450, 300, 50,
        30, 150, 200, 70, 120,
        90, 110, 100, 80, 20,
        40, 250, 700, 130, 500,
        600, 220, 350, 140, 35,
        25, 180, 450, 5, 15,
        60, 180, 160, 120, 18,
        45, 25, 75, 95, 400,
        900, 60, 140, 130, 850,
        320, 55, 40, 600, 500
    ],
    "Quantity": [
        10, 25, 15, 12, 50,
        60, 8, 6, 20, 30,
        18, 14, 40, 35, 100,
        45, 22, 5, 16, 4,
        7, 9, 11, 28, 55,
        70, 13, 8, 120, 150,
        25, 17, 10, 12, 80,
        33, 44, 27, 21, 6,
        9, 19, 31, 24, 3,
        14, 26, 38, 5, 7
    ]
}
products = pd.DataFrame(data)
products.to_csv("Pract2_2_products.csv", index=False, encoding="utf-8")

In [44]:
products = pd.read_csv("Pract2_2_products.csv")
products.head()

      Product     Category  Price  Quantity
0      Laptop  Electronics   1200        10
1  Smartphone  Electronics    800        25
2      Tablet  Electronics    450        15
3     Monitor  Electronics    300        12
4    Keyboard  Accessories     50        50

In [45]:
# Додайте новий стовпець "Виручка" як добуток ціни та кількості.
products["Salary"] = products["Price"] * products["Quantity"]
# Виведіть оновлений DataFrame.
products.head()

      Product     Category  Price  Quantity  Salary
0      Laptop  Electronics   1200        10   12000
1  Smartphone  Electronics    800        25   20000
2      Tablet  Electronics    450        15    6750
3     Monitor  Electronics    300        12    3600
4    Keyboard  Accessories     50        50    2500

## Завдання 5
Є список студентів із зазначенням: "Ім'я", "Курс", "Оцінка".
- Створіть DataFrame і заповніть його не менш ніж вісьмома рядками.
- Виведіть вихідний DataFrame.
- Обчисліть середню оцінку за кожним курсом.
- Знайдіть максимальну та мінімальну оцінку за кожним курсом.

In [46]:
data = {
    "Ім'я Прізвище": [
        "Іван Петренко", "Іван Петренко", "Іван Петренко", "Іван Петренко", "Іван Петренко",
        "Олена Коваль", "Олена Коваль", "Олена Коваль", "Олена Коваль", "Олена Коваль",
        "Андрій Шевченко", "Андрій Шевченко", "Андрій Шевченко", "Андрій Шевченко", "Андрій Шевченко",
        "Марія Бондар", "Марія Бондар", "Марія Бондар", "Марія Бондар", "Марія Бондар",
        "Дмитро Мельник", "Дмитро Мельник", "Дмитро Мельник", "Дмитро Мельник", "Дмитро Мельник",
        "Наталія Ткаченко", "Наталія Ткаченко", "Наталія Ткаченко", "Наталія Ткаченко", "Наталія Ткаченко",
        "Сергій Іваненко", "Сергій Іваненко", "Сергій Іваненко", "Сергій Іваненко", "Сергій Іваненко",
        "Юлія Сидоренко", "Юлія Сидоренко", "Юлія Сидоренко", "Юлія Сидоренко", "Юлія Сидоренко",
        "Володимир Кравець", "Володимир Кравець", "Володимир Кравець", "Володимир Кравець", "Володимир Кравець",
        "Тетяна Мороз", "Тетяна Мороз", "Тетяна Мороз", "Тетяна Мороз", "Тетяна Мороз"
    ],
    "Дисципліна": [
        "Математика", "Фізика", "Інформатика", "Історія", "Англійська мова",
        "Математика", "Фізика", "Інформатика", "Історія", "Англійська мова",
        "Математика", "Фізика", "Інформатика", "Історія", "Англійська мова",
        "Математика", "Фізика", "Інформатика", "Історія", "Англійська мова",
        "Математика", "Фізика", "Інформатика", "Історія", "Англійська мова",
        "Математика", "Фізика", "Інформатика", "Історія", "Англійська мова",
        "Математика", "Фізика", "Інформатика", "Історія", "Англійська мова",
        "Математика", "Фізика", "Інформатика", "Історія", "Англійська мова",
        "Математика", "Фізика", "Інформатика", "Історія", "Англійська мова",
        "Математика", "Фізика", "Інформатика", "Історія", "Англійська мова"
    ],
    "Оцінка": [
        95, 88, 92, 85, 90,
        89, 91, 94, 87, 93,
        78, 82, 85, 80, 84,
        96, 94, 98, 92, 95,
        73, 77, 81, 75, 79,
        88, 86, 90, 84, 89,
        91, 89, 93, 88, 92,
        85, 83, 87, 81, 86,
        79, 76, 82, 78, 80,
        94, 92, 96, 90, 95
    ]
}
marks = pd.DataFrame(data)
marks.head(10)

   Ім'я Прізвище       Дисципліна  Оцінка
0  Іван Петренко       Математика      95
1  Іван Петренко           Фізика      88
2  Іван Петренко      Інформатика      92
3  Іван Петренко          Історія      85
4  Іван Петренко  Англійська мова      90
5   Олена Коваль       Математика      89
6   Олена Коваль           Фізика      91
7   Олена Коваль      Інформатика      94
8   Олена Коваль          Історія      87
9   Олена Коваль  Англійська мова      93

In [50]:
# Обчисліть середню оцінку за кожним курсом.
results = marks.groupby("Дисципліна")["Оцінка"]
print("середня оцінка за кожним курсом:", results.mean(), sep='\n')

середня оцінка за кожним курсом:
Дисципліна
Інформатика        89.8
Історія            84.0
Англійська мова    88.3
Математика         86.8
Фізика             85.8
Name: Оцінка, dtype: float64

In [51]:
# Знайдіть максимальну та мінімальну оцінку за кожним курсом.
print("мінімальна оцінка за кожним курсом:", results.min(), sep='\n')
print("максимальна оцінка за кожним курсом:", results.max(), sep='\n')

мінімальна оцінка за кожним курсом:
Дисципліна
Інформатика        81
Історія            75
Англійська мова    79
Математика         73
Фізика             76
Name: Оцінка, dtype: int64
максимальна оцінка за кожним курсом:
Дисципліна
Інформатика        98
Історія            92
Англійська мова    95
Математика         96
Фізика             94
Name: Оцінка, dtype: int64

In [52]:
# Вивести середні бали по студентам

## Завдання 6
Зібрано дані про товари та продажі у двох таблицях. Перша містить: "ID", "Назва", "Ціна". Друга містить: "ID", "Кількість".
- Створіть два DataFrame і заповніть їх не менш ніж п'ятьма рядками.
- Виведіть обидва DataFrame.
- Об'єднайте їх за колонкою "ID".
- Додайте новий стовпець "Сума" як добуток ціни та кількості.
- Виведіть підсумковий DataFrame.

In [53]:
stock = pd.DataFrame({
    "ID":[1,2,3,4,5], 
    "Назва":["Laptop", "Smartphone", "Tablet", "Monitor", "Keyboard"], 
    "Ціна":[1200, 800, 450, 300, 50]
})
stock

   ID       Назва  Ціна
0   1      Laptop  1200
1   2  Smartphone   800
2   3      Tablet   450
3   4     Monitor   300
4   5    Keyboard    50

In [54]:
sales = pd.DataFrame({
    "ID":[1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5], 
    "Кількість":[2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1]
})
sales.head()

   ID  Кількість
0   1          2
1   2          3
2   3          4
3   4          5
4   5          1

In [56]:
# Об'єднайте їх за колонкою "ID".
merged = pd.merge(stock, sales, on="ID", how="inner")
merged.head(7)

   ID       Назва  Ціна  Кількість
0   1      Laptop  1200          2
1   1      Laptop  1200          2
2   1      Laptop  1200          2
3   1      Laptop  1200          2
4   2  Smartphone   800          3
5   2  Smartphone   800          3
6   2  Smartphone   800          3

In [ ]:
# Додайте новий стовпець "Сума" як добуток ціни та кількості.
# Виведіть підсумковий DataFrame.